var $refs = {
    resultCanvas: jQuery(".resultCanvas"),
    preview: jQuery(".preview"),
    previewCanvas: jQuery(".preview__canvas"),
    previewOutOfBoundsCanvas: jQuery(".preview__outOfBoundsCanvas"),
    previewCanvasToolbar: jQuery(".preview__canvasToolbar"),
    configForm: jQuery(".config"),
    resultPNGDataInput: jQuery(".config_resultPNGDataInput"),
    resultCombinedPNGDataInput: jQuery(".config_resultCombinedPNGDataInput"),
    resultCardCanvas: jQuery(".resultCardCanvas"),
    downloadBtnCard: jQuery(".preview__download_card"),
    frameCodeSelect: jQuery(".config__selectFrameCode"),
    preconfigurationsTemplate: jQuery(".config__preconfigurationsTemplate"),
    preconfigurationsOptions: jQuery(".config__preconfigurationsOptions"),
    maskElementsTemplate: jQuery(".config__maskElementsTemplate"),
    maskElementsOptions: jQuery(".config__maskElementsOptions"),
    uploadDesignSecondaryColor: jQuery(".config__uploadDesignSecondaryColor"),
    removeSecondary: jQuery(".config__removeSecondary"),
    removeImage: jQuery(".config__removeImage"),
    chooseImage: jQuery(".preview__chooseImage"),
    zoomBtn: jQuery(".preview__toggleZoom"),
    lockBtn: jQuery(".preview__toggleLock"),
    submitBtn: jQuery(".preview__submit"),
    resetBtn: jQuery(".preview__reset"),
    downloadBtn: jQuery(".preview__download"),
    uploadDesignInput: jQuery(".config__uploadDesign"),
    uploadDesignColor: jQuery(".config__uploadDesignColor"),
    configFrameCode: jQuery(".config__frameCode"),
    configUpload: jQuery(".config__upload"),
    configOptions: jQuery(".config__options"),
    //for another image
    uploadDesignInputSecondary: jQuery(".config__uploadDesignSecondary"),
    uploadDesignMaskTransparent: jQuery(".config__uploadDesignMaskTransparent"),
    uploadSecondaryMaskTransparent: jQuery(".config__uploadSecondaryMaskTransparent"),

}